### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by BrandenBedoya** [xpertdev/Bjs-Wholesale-Coupon-Bot#1]
Hi there,

This used to work for me (the last 2 months or so) and I just tried running it but it keeps giving an error for each line (coupon) it runs. 

Error 1:
myCoupons:2094 Uncaught ReferenceError: $ is not defined
    at <anonymous>:7:19
    at o (LogRocket.min.js:2:4582)
    at nrWrapper (myCoupons:2092:39)

Error 2:
The following item cannot be handled by the data layer because it does not have a valid format: {"0":"event","1":"page_view","2":{"send_to":"AW-10858302079"}}

**Comment by xpertdev** [comment]
There is still some issue but give this a try https://github.com/xpertdev/Bjs-Wholesale-Coupon-Bot/tree/issue-fix-broken-clicks
